# Generated by Django 3.2.12 on 2023-07-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_traveling_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
