# Generated by Django 3.2.12 on 2023-07-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menu_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuChildren',
        ),
    ]
