# Generated by Django 3.2.12 on 2023-07-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_menuchildren'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveling',
            name='guarantee',
            field=models.CharField(max_length=5),
        ),
    ]
